config/routes.rb
Rails.application.routes.draw do
  resources :recipes do
    resources :ingredients
    delete 'delete_recipe', to: 'recipes#delete_recipe', as: :delete_recipe_recipe
  end

  resources :grocery_lists do
    get 'add_recipes', on: :member
    post 'add_recipes', on: :member
  end

  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/grocery_list.rb
class GroceryList < ApplicationRecord
  has_many :grocery_list_recipes
  has_many :recipes, through: :grocery_list_recipes
end

app/models/grocery_list_recipe.rb
class GroceryListRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :grocery_list
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :name, :amount, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :grocery_list_recipes
  has_many :grocery_lists, through: :grocery_list_recipes
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/grocery_lists_controller.rb
class GroceryListsController < ApplicationController
  before_action :set_grocery_list, only: [:show, :edit, :update, :destroy, :add_recipes]

  def index
    @grocery_lists = GroceryList.all
  end

  def show
  end

  def new
    @grocery_list = GroceryList.new
  end

  def create
    @grocery_list = GroceryList.new(grocery_list_params)

    if @grocery_list.save
      redirect_to @grocery_list, notice: 'Grocery list was successfully created.'
    else
      render :new
    end
  end

  def add_recipes
    if request.post?
      @grocery_list.recipes = Recipe.where(id: params[:recipe_ids])
      redirect_to @grocery_list, notice: 'Recipes were successfully added.'
    else
      @recipes = Recipe.all
    end
  end

  private
    def set_grocery_list
      @grocery_list = GroceryList.find(params[:id])
    end

    def grocery_list_params
      params.require(:grocery_list).permit(:name)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # before any recipe action, set the recipe
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    # get all recipes in descending order
    @recipes = Recipe.all.order(created_at: :desc)
  end

  def show
    # show a single recipe
    # before_action has set @recipe for us
  end

  def new
    # build a new recipe and multiple ingredients
    @recipe = Recipe.new
    3.times { @recipe.ingredients.build }  # Replace "3" with the desired number of initial ingredients
  end

  def create
    # create a new recipe from params
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      # if the save was successful, redirect to the index action
      redirect_to recipes_path, notice: 'Recipe was successfully created.'
    else
      # otherwise render the new template
      render :new
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path, notice: 'Recipe was successfully deleted.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(:name, :description, :instructions, :special_notes, ingredients_attributes: [:id, :name, :amount, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grocery_lists_helper.rb
module GroceryListsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/grocery_lists/add_recipes.html.erb
<h1>Add Recipes to <%= @grocery_list.name %></h1>

<%= form_with url: add_recipes_grocery_list_path(@grocery_list), method: :post, local: true do |form| %>
  <div class="field">
    <%= collection_check_boxes(:recipe_ids, :id, @recipes, :id, :name) %>
  </div>

  <%= form.submit 'Add Recipes' %>
<% end %>

<%= link_to 'Back', @grocery_list %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeManagementSystem</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>

    <!-- Add the following code -->
    <script src="/assets/delete_recipe.js"></script>
    <script src="/assets/recipes.js"></script>
    <!-- End of added code -->

  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipe Cards</h1>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= link_to 'Add Recipe Card', new_recipe_path %>

<div class="recipes">
  <% @recipes.each do |recipe| %>
    <div class="recipe">
      <%= link_to recipe.name, recipe_path(recipe) %>
    </div>
  <% end %>
  <%= link_to 'Create Grocery List', new_grocery_list_path %>

</div>

app/views/recipes/new.html.erb
<h1>Add Recipe Card</h1>

<% if @recipe.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @recipe, local: true) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :instructions %>
    <%= form.text_area :instructions %>
  </div>

  <div class="field">
    <%= form.label :special_notes %>
    <%= form.text_area :special_notes %>
  </div>

  <div class="ingredients">
    <%= form.fields_for :ingredients do |ingredient_form| %>
      <div class="ingredient">
        <%= ingredient_form.label :name %>
        <%= ingredient_form.text_field :name %>

        <%= ingredient_form.label :amount %>
        <%= ingredient_form.text_field :amount %>
      </div>
    <% end %>
    <%= link_to 'Add Ingredient', '', class: 'add_ingredient' %>
  </div>

  <%= form.submit %>
<% end %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>

<p>
  <strong>Special notes:</strong>
  <%= @recipe.special_notes %>
</p>

<h2>Ingredients</h2>
<ul>
  <% @recipe.ingredients.each do |ingredient| %>
    <li><%= ingredient.name %> - <%= ingredient.amount %></li>
  <% end %>
</ul>

<%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' }, class: 'btn btn-danger', id: 'delete-recipe' %>
<%= link_to 'Back', recipes_path %>